# Generated by Django 4.1.2 on 2022-11-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcolormodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='colors',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colorsR',
            field=models.ManyToManyField(related_name='products', to='products.productcolormodel'),
        ),
    ]
