# Generated by Django 4.1.2 on 2022-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productmodel_colors_productmodel_colorsr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='colorsR',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.productcolormodel'),
        ),
    ]
